# Generated by Django 6.0.3 on 2026-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('step', models.CharField(default='welcome', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'onboarding_progress',
                'managed': False,
            },
        ),
    ]
