# Generated by Django 6.0.3 on 2026-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('description_pattern', models.CharField(max_length=255)),
                ('category_id', models.UUIDField()),
                ('frequency', models.IntegerField(default=1)),
                ('last_used_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'categorization_history',
                'managed': False,
            },
        ),
    ]
