# Generated by Django 6.0.3 on 2026-03-21 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('analysis_type', models.CharField(choices=[('expense_analysis', 'Expense Analysis'), ('budget_recommendation', 'Budget Recommendation')], max_length=30)),
                ('input_summary', models.JSONField()),
                ('result', models.JSONField()),
                ('model_used', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'analysis_history',
                'managed': False,
            },
        ),
    ]
