# Generated by Django 6.0.3 on 2026-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_sessions',
                'managed': False,
            },
        ),
    ]
